export { default as Header } from './Header'
export { default as About } from './About'
export { default as Products } from './Products'
export { default as Suits } from './Suits'
export { default as Tailoring } from './Tailoring'
export { default as Contact } from './Contact'
export { default as Navbar } from './Navbar'